# Tests for drugs_remimazolam.R (Eleveld 2025 model). Remimazolam was the
# only drug (besides oliceridine) without a test file.
#
# The model scales allometrically with weight (Fsize = weight/70), v3 grows
# with age, and v3 carries a female factor. NOTE / pinned quirk: the code
# computes Fcl1_sex for females (exp(16.3/100)) but never multiplies it into
# cl1, so cl1 currently depends only on weight. The snapshot below asserts
# that CURRENT behavior; if the sex factor is intended, fixing it will (and
# should) fail this test, prompting a deliberate update. Flagged on the
# drug-library test-plan issue.
#
# The reference is asserted via author substring so the test survives
# citation-formatting updates (drug-reference-citations work).
#
# Provenance: drafted by Claude Code (Opus 4.8), 2026-08-14, for the
# pre-deployment test plan (drug library). Expected values generated by
# running drugs_remimazolam.R and hand-checking the covariate algebra.

test_that("returns the correct calculations for the reference male", {
  # weight 70 => Fsize = 1; age 35 => Fv3_age = 1; male => no sex factors.
  # So the reference patient returns the raw model constants.
  actual <- remimazolam(weight = 70, height = 170, age = 35, sex = "male")

  expect_equal_rounded(
    actual$PK,
    list(
      default = list(
        v1 = 4.31,
        v2 = 12.3,
        v3 = 18.6,
        cl1 = 1.12,
        cl2 = 1.45,
        cl3 = 0.298
      )
    )
  )
  expect_equal(actual$tPeak, 2.5)
  expect_match(actual$reference, "Eleveld")
})

test_that("returns the correct calculations for a female with age scaling", {
  # weight 60 => Fsize = 6/7; age 60 => Fv3_age = exp(0.00731*25);
  # female => Fv3_sex = exp(0.287). cl2/cl3 rescale from v2/v3.
  actual <- remimazolam(weight = 60, height = 165, age = 60, sex = "female")

  expect_equal_rounded(
    actual$PK,
    list(
      default = list(
        v1 = 3.694286,
        v2 = 10.54286,
        v3 = 25.5021,
        cl1 = 0.9977183,
        cl2 = 1.291689,
        cl3 = 0.377584
      )
    )
  )
})

test_that("weight scaling is allometric", {
  a <- remimazolam(70, 170, 35, "male")$PK$default
  b <- remimazolam(140, 170, 35, "male")$PK$default
  expect_equal(b$v1 / a$v1, 2)              # volumes scale linearly
  expect_equal(b$cl1 / a$cl1, 2^0.75)       # clearance scales to the 3/4 power
})

test_that("v3 increases with age and with female sex", {
  young <- remimazolam(70, 170, 35, "male")$PK$default
  old   <- remimazolam(70, 170, 80, "male")$PK$default
  expect_gt(old$v3, young$v3)

  male   <- remimazolam(70, 170, 35, "male")$PK$default
  female <- remimazolam(70, 170, 35, "female")$PK$default
  expect_gt(female$v3, male$v3)
})

test_that("cl1 currently ignores the female factor (pinned quirk)", {
  # Fcl1_sex is computed in the code but never applied; see file header.
  male   <- remimazolam(70, 170, 35, "male")$PK$default
  female <- remimazolam(70, 170, 35, "female")$PK$default
  expect_equal(female$cl1, male$cl1)
})

test_that("return structure has the fields the engine consumes", {
  actual <- remimazolam(70, 170, 35, "male")
  expect_named(
    actual,
    c("PK", "tPeak", "MEAC", "typical", "upperTypical", "lowerTypical",
      "reference")
  )
  expect_named(actual$PK, "default")
  expect_named(actual$PK$default, c("v1", "v2", "v3", "cl1", "cl2", "cl3"))
  pk <- actual$PK$default
  expect_true(all(unlist(pk) > 0))
  expect_gt(actual$tPeak, 0)
})
