# Workflow for cleaning up deployed Shiny apps after PR closure
name: Shiny PR 3 Cleanup

on:
  pull_request_target:
    types: [closed]

jobs:
  cleanup-pr:
    runs-on: ubuntu-24.04
    if: contains(github.event.pull_request.labels.*.name, 'DEPLOY')
    permissions:
      pull-requests: write
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Delete app
        env:
          SHINY_APP_NAME: ${{ vars.PR_SHINY_APP_NAME }}_PR_${{ github.event.pull_request.number }}
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo("${{ vars.PR_SHINY_ACCOUNT }}", "${{ secrets.PR_SHINY_TOKEN }}", "${{ secrets.PR_SHINY_SECRET }}")
          rsconnect::terminateApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ vars.PR_SHINY_ACCOUNT }}")
          rsconnect::purgeApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ vars.PR_SHINY_ACCOUNT }}")
        shell: Rscript {0}
      - name: Remove DEPLOY label
        if: always()   # even if previous step fails
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'DEPLOY'
              });
            } catch (e) {
              console.log("Label `DEPLOY` not found, skipping removal.");
            }
